# Generated by Django 3.1.7 on 2021-03-22 19:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Courier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courier_id', models.IntegerField(db_index=True, verbose_name='courier_id')),
                ('courier_type', models.IntegerField(choices=[(1, 'foot'), (2, 'bike'), (3, 'car')], verbose_name='courier_type')),
                ('regions', models.IntegerField(db_index=True, verbose_name='regions')),
                ('working_hours', models.DateField(max_length=64, verbose_name='working_hours')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
    ]
