# Generated by Django 3.1.7 on 2021-03-22 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lollipops', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courier',
            name='courier_id',
            field=models.IntegerField(db_index=True, unique=True, verbose_name='courier_id'),
        ),
    ]
