# Generated by Django 3.1.7 on 2021-03-27 18:15

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lollipops', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='courier',
            name='rating',
            field=models.PositiveSmallIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='courier',
            name='working_hours',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=128, null=True), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_hours',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=128, null=True), blank=True, null=True, size=None),
        ),
    ]
