# Generated by Django 3.1.7 on 2021-03-27 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lollipops', '0003_auto_20210327_2121'),
    ]

    operations = [
        migrations.AddField(
            model_name='courier',
            name='earnings',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True),
        ),
    ]
