# Generated by Django 3.1.7 on 2021-03-27 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lollipops', '0004_courier_earnings'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='assign_time',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='order',
            name='complete_time',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(blank=True, default='In processing', max_length=30),
        ),
    ]
