# Generated by Django 3.1.7 on 2021-03-27 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lollipops', '0005_auto_20210327_2130'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='courier_id_delivery',
            field=models.IntegerField(blank=True, default=-1),
        ),
    ]
