# Generated by Django 3.1.7 on 2021-03-23 19:10

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lollipops', '0005_remove_courier_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courier',
            name='working_hours',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=128, verbose_name='working_hours'), size=None),
        ),
    ]
