# Generated by Django 3.1.7 on 2021-03-23 23:38

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lollipops', '0007_auto_20210324_0236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courier',
            name='regions',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True, null=True), blank=True, null=True, size=None),
        ),
    ]
