# Generated by Django 3.1.7 on 2021-03-24 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lollipops', '0008_auto_20210324_0238'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courier',
            name='id',
        ),
        migrations.AlterField(
            model_name='courier',
            name='courier_id',
            field=models.PositiveIntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
