# Generated by Django 3.1.7 on 2021-03-29 15:33

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lollipops', '0009_auto_20210329_1812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courier',
            name='completed_orders',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveIntegerField(blank=True, null=True), blank=True, null=True, size=None), blank=True, default=[], null=True, size=None),
        ),
    ]
