# Generated by Django 3.1.7 on 2021-03-24 09:48

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lollipops', '0009_auto_20210324_1214'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('order_id', models.PositiveIntegerField(primary_key=True, serialize=False, unique=True)),
                ('weight', models.FloatField(blank=True, null=True)),
                ('region', models.IntegerField(blank=True, null=True)),
                ('delivery_hours', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=128, null=True), blank=True, null=True, size=None)),
            ],
        ),
    ]
