# Generated by Django 3.1.7 on 2021-03-24 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lollipops', '0010_orders'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Orders',
            new_name='Order',
        ),
    ]
