# Generated by Django 3.1.7 on 2021-03-27 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lollipops', '0011_auto_20210324_1517'),
    ]

    operations = [
        migrations.AddField(
            model_name='courier',
            name='earnings',
            field=models.PositiveSmallIntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='courier',
            name='rating',
            field=models.PositiveSmallIntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='assign_time',
            field=models.CharField(blank=True, default='0', max_length=10),
        ),
        migrations.AddField(
            model_name='order',
            name='complete_time',
            field=models.CharField(blank=True, default='0', max_length=10),
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(blank=True, default='In processing', max_length=10),
        ),
    ]
