# Generated by Django 3.1.7 on 2021-03-27 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lollipops', '0013_auto_20210327_2013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(blank=True, default='Got', max_length=100),
        ),
    ]
