# Generated by Django 3.1.7 on 2021-03-27 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lollipops', '0014_auto_20210327_2014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courier',
            name='earnings',
            field=models.PositiveSmallIntegerField(blank=True, default=1),
        ),
        migrations.AlterField(
            model_name='courier',
            name='rating',
            field=models.PositiveSmallIntegerField(blank=True, default=1),
        ),
    ]
