# Generated by Django 3.1.7 on 2021-03-27 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lollipops', '0015_auto_20210327_2015'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='assign_time',
        ),
        migrations.RemoveField(
            model_name='order',
            name='complete_time',
        ),
        migrations.RemoveField(
            model_name='order',
            name='status',
        ),
    ]
