# Generated by Django 3.1.7 on 2021-03-27 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lollipops', '0016_auto_20210327_2016'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courier',
            name='earnings',
        ),
        migrations.RemoveField(
            model_name='courier',
            name='rating',
        ),
        migrations.AddField(
            model_name='order',
            name='assign_time',
            field=models.CharField(blank=True, default='0', max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='complete_time',
            field=models.CharField(blank=True, default='0', max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(blank=True, default='Got', max_length=100),
        ),
    ]
