# Generated by Django 3.1.7 on 2021-03-27 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lollipops', '0018_auto_20210327_2017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courier',
            name='earnings',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='courier',
            name='rating',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
