# Generated by Django 3.1.7 on 2021-03-27 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lollipops', '0020_auto_20210327_2020'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courier',
            name='rating',
        ),
    ]
